name: Docker Hub

# on all branches, tags, PRs
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push WEB
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.web
          push: ${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/') }}
          tags: pawr/tribes-web:latest
      -
        name: Build and push CRON
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.cron
          push: ${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/') }}
          tags: pawr/tribes-cron:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
